marvel:
    resource: "@MarvelBundle/Resources/config/routing.yml"
    prefix:   /home

home:
    path:     /
    defaults: { _controller: MarvelBundle:Default:home }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
